export const studentData = [
    {
        name: "John Doe",
        email: "john.doe@example.com",
        photoUrl: "https://randomuser.me/api/portraits/men/1.jpg"
    },
    {
        name: "Jane Smith",
        email: "jane.smith@example.com",
        photoUrl: "https://randomuser.me/api/portraits/women/2.jpg"
    },
    {
        name: "Michael Johnson",
        email: "michael.johnson@example.com",
        photoUrl: "https://randomuser.me/api/portraits/men/3.jpg"
    },
    {
        name: "Emily Brown",
        email: "emily.brown@example.com",
        photoUrl: "https://randomuser.me/api/portraits/women/4.jpg"
    },
    {
        name: "David Williams",
        email: "david.williams@example.com",
        photoUrl: "https://randomuser.me/api/portraits/men/5.jpg"
    },
];
export const userRows = [
    {
        id: 1,
        img: "https://randomuser.me/api/portraits/men/1.jpg",
        lastName: "Smith",
        firstName: "John",
        email: "john.smith@example.com",
        courseTaken: 3,
        createdAt: "01.02.2023",
        verified: true,
    },
    {
        id: 2,
        img: "https://randomuser.me/api/portraits/women/1.jpg",
        lastName: "Johnson",
        firstName: "Emma",
        email: "emma.johnson@example.com",
        courseTaken: 2,
        createdAt: "01.02.2023",
        verified: true,
    },
    {
        id: 3,
        img: "https://randomuser.me/api/portraits/men/3.jpg",
        lastName: "Williams",
        firstName: "Michael",
        email: "michael.williams@example.com",
        courseTaken: 30,
        createdAt: "01.02.2023",
        verified: false,
    },
    {
        id: 4,
        img: "https://randomuser.me/api/portraits/women/2.jpg",
        lastName: "Brown",
        firstName: "Olivia",
        email: "olivia.brown@example.com",
        courseTaken: 14,
        createdAt: "01.02.2023",
        verified: true,
    },
    {
        id: 5,
        img: "https://randomuser.me/api/portraits/women/3.jpg",
        lastName: "Garcia",
        firstName: "Sophia",
        email: "sophia.garcia@example.com",
        courseTaken: 55,
        createdAt: "01.02.2023",
        verified: true,
    },
    {
        id: 6,
        img: "https://randomuser.me/api/portraits/men/4.jpg",
        lastName: "Martinez",
        firstName: "Daniel",
        email: "daniel.martinez@example.com",
        courseTaken: 6,
        createdAt: "01.02.2023",
        verified: false,
    },
    {
        id: 7,
        img: "https://randomuser.me/api/portraits/women/5.jpg",
        lastName: "Rodriguez",
        firstName: "Isabella",
        email: "isabella.rodriguez@example.com",
        courseTaken: 11,
        createdAt: "01.02.2023",
        verified: true,
    },
    {
        id: 8,
        img: "https://randomuser.me/api/portraits/men/6.jpg",
        lastName: "Hernandez",
        firstName: "Alexander",
        email: "alexander.hernandez@example.com",
        courseTaken: 9,
        createdAt: "01.02.2023",
        verified: true,
    },
    {
        id: 9,
        img: "https://randomuser.me/api/portraits/women/6.jpg",
        lastName: "Lopez",
        firstName: "Mia",
        email: "mia.lopez@example.com",
        courseTaken: 12,
        createdAt: "01.02.2023",
        verified: true,
    },
    {
        id: 10,
        img: "https://randomuser.me/api/portraits/men/7.jpg",
        lastName: "Gonzalez",
        firstName: "Liam",
        email: "liam.gonzalez@example.com",
        courseTaken: 22,
        createdAt: "01.02.2023",
        verified: true,
    },
    {
        id: 11,
        img: "https://randomuser.me/api/portraits/women/7.jpg",
        lastName: "Perez",
        firstName: "Ava",
        email: "ava.perez@example.com",
        courseTaken: 32,
        createdAt: "01.02.2023",
        verified: false,
    },
    {
        id: 12,
        img: "https://randomuser.me/api/portraits/men/8.jpg",
        lastName: "Torres",
        firstName: "Noah",
        email: "noah.torres@example.com",
        courseTaken: 24,
        createdAt: "01.02.2023",
        verified: true,
    },
    {
        id: 13,
        img: "https://randomuser.me/api/portraits/women/8.jpg",
        lastName: "Rivera",
        firstName: "Emma",
        email: "emma.rivera@example.com",
        courseTaken: 13,
        createdAt: "01.02.2023",
        verified: true,
    },
    {
        id: 14,
        img: "https://randomuser.me/api/portraits/women/9.jpg",
        lastName: "Morgan",
        firstName: "Oliver",
        email: "oliver.morgan@example.com",
        courseTaken: 4,
        createdAt: "01.02.2023",
        verified: false,
    },
    {
        id: 15,
        img: "https://randomuser.me/api/portraits/women/10.jpg",
        lastName: "Davis",
        firstName: "Amelia",
        email: "amelia.davis@example.com",
        courseTaken: 15,
        createdAt: "01.02.2023",
        verified: true,
    },

];
export const singleStudent = {
    id: 1,
    title: "John Doe",
    img: "https://randomuser.me/api/portraits/men/1.jpg",
    info: {
        Username: "JohnSmith",
        Fullname: "John Smith",
        Email: "john.smith@example.com",
        CoursesTaken: "3",
        Status: "verified",
    },
    chart: {
        dataKeys: [
            { name: "visits", color: "#82ca88" },
            { name: "clicks", color: "#8884d7" },
        ],
        data: [
            {
                name: "Sun",
                visits: 4500,
                clicks: 2800,
            },
            {
                name: "Mon",
                visits: 3200,
                clicks: 1500,
            },
            {
                name: "Tue",
                visits: 2100,
                clicks: 4100,
            },
            {
                name: "Wed",
                visits: 3000,
                clicks: 4200,
            },
            {
                name: "Thu",
                visits: 2200,
                clicks: 5000,
            },
            {
                name: "Fri",
                visits: 2600,
                clicks: 4200,
            },
            {
                name: "Sat",
                visits: 3700,
                clicks: 4700,
            },
        ],
    },
    courses: [
        {
            img: "web",
            text: "Web devepoment",
            time: "3 day ago",
        },
        {
            img: "machine",
            text: "Machine Learning",
            time: "1 week ago",
        },
        {
            img: "ui",
            text: "UI/UX Design",
            time: "2 weeks ago",
        },

    ],
};